package idref

import (
	"reflect"
	"testing"
)

type docsGetTest struct {
	Description string
	Input       string
	Expected    Documents
	Valid       bool
}

func TestDocsGet(t *testing.T) {
	var docsGetTestCases = []docsGetTest{
		{
			Description: "Docs for single PPN, valid Org: Université du Rwanda",
			Input:       "02797524X",
			Expected: Documents{
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "000",
					Marc21Code:  "000",
					RoleName:    "Code de fonction non reconnu",
				},
					Citation: "Uruhare rw'umuco mu kubaka umuryango nyarwanda  [Texte imprimé] / [Kigali] : Editions de l'Université nationale du Rwanda , 2007",
					ID:       "161811310",
					Source:   "sudoc",
					URI:      "",
					URL:      "",
				},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "000",
					Marc21Code:  "000",
					RoleName:    "Code de fonction non reconnu"},
					Citation: "Afrique des grands lacs  [Texte imprimé]  : sécurité et paix durable  / sous la direction de Anastase Shyaka et Faustin Rutembesa / Butare [Rwanda] : Editions de l'Université nationale du Rwanda , 2004",
					ID:       "091610540",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "000",
					Marc21Code:  "000",
					RoleName:    "Code de fonction non reconnu"},
					Citation: "Textes légaux et réglementaires de l'Université nationale du Rwanda de 1963 à 1985  / Université nationale du Rwanda / Butare : Secrétariat général de l'Université , [1986]",
					ID:       "020539835",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "070",
					Marc21Code:  "aut",
					RoleName:    "Auteur"},
					Citation: "L'informateur / Butare : Université nationale du Rwanda , 1967-1973",
					ID:       "036322539",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "070",
					Marc21Code:  "aut",
					RoleName:    "Auteur"},
					Citation: "Etudes rwandaises / Butare : Université nationale du Rwanda , 1986-",
					ID:       "040136582",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "070",
					Marc21Code:  "aut",
					RoleName:    "Auteur"},
					Citation: "Rapport annuel, année académique ... Texte imprimé / Université nationale du Rwanda, Campus universitaire de Butare / Butare (Rwanda) Université nationale du Rwanda    ",
					ID:       "34410066",
					Source:   "bnf",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "070",
					Marc21Code:  "aut",
					RoleName:    "Auteur"},
					Citation: "Université nationale du Rwanda, 25 ans après Texte imprimé / Butare Université nationale 1988   ",
					ID:       "36680938",
					Source:   "bnf",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "070",
					Marc21Code:  "aut",
					RoleName:    "Auteur"},
					Citation: "Les cours universitaires Texte imprimé / Université nationale du Rwanda / Ruhengeri Université nationale du Rwanda 198-?-   ",
					ID:       "34281656",
					Source:   "bnf",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "070",
					Marc21Code:  "aut",
					RoleName:    "Auteur"},
					Citation: "Muntu Texte imprimé / Butare Editions universitaires du Rwanda 1969-   ",
					ID:       "34246336",
					Source:   "bnf",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "070",
					Marc21Code:  "aut",
					RoleName:    "Auteur"},
					Citation: "L' Informateur de l'Université nationale du Rwanda Texte imprimé / Butaré, RWA     ",
					ID:       "34467135",
					Source:   "bnf",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "070",
					Marc21Code:  "aut",
					RoleName:    "Auteur"},
					Citation: "Annuaire - Université nationale du Rwanda Texte imprimé / publié par le Secrétariat général de l'Universté nationale du Rwanda / Butare Université nationale du Rwanda 1968/1969-   ",
					ID:       "34473540",
					Source:   "bnf",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "070",
					Marc21Code:  "aut",
					RoleName:    "Auteur"},
					Citation: "L'Informateur de l'Université nationale du Rwanda Texte imprimé / dir. Elzéar Lavoie / Butare [s.n.]    ",
					ID:       "34493640",
					Source:   "bnf",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "070",
					Marc21Code:  "aut",
					RoleName:    "Auteur"},
					Citation: "Etudes Rwandaises Texte imprimé / Université nationale du Rwanda / Butare Université nationale du Rwanda 1977-   ",
					ID:       "34489522",
					Source:   "bnf",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "070",
					Marc21Code:  "aut",
					RoleName:    "Auteur"},
					Citation: "Etudes rwandaises. Texte imprimé / Butaré, RWA     ",
					ID:       "34466003",
					Source:   "bnf",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "070",
					Marc21Code:  "aut",
					RoleName:    "Auteur"},
					Citation: "Revue juridique du Rwanda Texte imprimé ; Faculté de droit / Ministère de la justice / Kigali Faculté de droit Ministère de la justice 1977-   ",
					ID:       "38986345",
					Source:   "bnf",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "070",
					Marc21Code:  "aut",
					RoleName:    "Auteur"},
					Citation: "[Annuaire] Texte imprimé / [Université nationale du Rwanda] / Butare Université nationale du Rwanda. Secrétariat géneral    ",
					ID:       "34463104",
					Source:   "bnf",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "295",
					Marc21Code:  "dgg",
					RoleName:    "Organisme de soutenance"},
					Citation: "Le commerce des esclaves au Rwanda  [Texte imprimé]  / par Mujawimana Eugénie  ; sous la direction du Père Roger Heremans / [S.l.] : [s.n.] , 1983",
					ID:       "137294301",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "295",
					Marc21Code:  "dgg",
					RoleName:    "Organisme de soutenance"},
					Citation: "Etude sur trois mythes rwandais  [Texte imprimé]  : essai d'interprétation psychanalytique  / Vénéranda Kantengwa / [S.l.] : [s.n.] , 1982",
					ID:       "073718254",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "295",
					Marc21Code:  "dgg",
					RoleName:    "Organisme de soutenance"},
					Citation: "Analyse typologique du récit rwandais  [Texte imprimé]  / Jotham Nsanganira / [S.l.] : [s.n.] , 1979",
					ID:       "073718335",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "295",
					Marc21Code:  "dgg",
					RoleName:    "Organisme de soutenance"},
					Citation: "La Littérature rwandaise  [Texte imprimé]  : bilan, problèmes et perspectives  / François-Xavier Munyarugerero / [S.l.] : [s.n.] , 1982",
					ID:       "073718157",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "295",
					Marc21Code:  "dgg",
					RoleName:    "Organisme de soutenance"},
					Citation: "L'Importance de la vache dans les relations socio-économiques du Rwanda précolonial  [Texte imprimé]  / Marie-Espérance Dusengeyezu / [S.l.] : [s.n.] , 1978",
					ID:       "073717150",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "295",
					Marc21Code:  "dgg",
					RoleName:    "Organisme de soutenance"},
					Citation: "Contribution à l'étude de l'avifaune de la région rizicole de Cyili (Butare) et de son impact sur les cultures du riz  [Texte imprimé]  / par Samuel Kanyamibwa  ; dir. Dr. A. Dragesco / [S.l.] : [s.n.] , 1986",
					ID:       "167128418",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "340",
					Marc21Code:  "edt",
					RoleName:    "Editeur scientifique"},
					Citation: "L' explosion démographique au Rwanda  : la place du planning familial  / Gérard Sledsens. Université Nationale du Rwanda / [Butaré] : [éditeur inconnu] , 1971",
					ID:       "230334164",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "340",
					Marc21Code:  "edt",
					RoleName:    "Editeur scientifique"},
					Citation: "Recherche linguistique et formation des formateurs  : bilan, évaluation des matériels didactiques  : actes de la VIIe Table ronde des centres, départements et instituts de linguistique appliquée d'Afrique noire  / organisée par l'AUPELF et l'Université nationale du Rwanda avec le concours du CIRELFA (A.C.C.T.), du Gouvernement français et de l'UNESCO, Kigali, 14-22 janvier 1987 / Montréal : AUPELF , 1988",
					ID:       "003290115",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "340",
					Marc21Code:  "edt",
					RoleName:    "Editeur scientifique"},
					Citation: "Aménagement des marais au Rwanda  [Texte imprimé]  : actes du colloque Butare, 5-7 juin 2001  : projet EAP-RW (DGCD-CUD-FUNDP-UNR)  / C. K. Kanangire, J.-C. Micha & J.-B. M. Gashagaza  ; Université nationale du Rwanda (UNR), D.G.C.D., C.U.D., Facultés universitaires Notre-Dame de la Paix (FUNDP) / Namur : Presses universitaires de Namur , 2004",
					ID:       "081206739",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "340",
					Marc21Code:  "edt",
					RoleName:    "Editeur scientifique"},
					Citation: "Enquête sur les recherches - recherche nouvelle  [Texte imprimé] / Butare : Université nationale du Rwanda , 1971",
					ID:       "113909772",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "340",
					Marc21Code:  "edt",
					RoleName:    "Editeur scientifique"},
					Citation: "Les relations interethniques au Rwanda à la lumière de l'agression d'octobre 1990 Texte imprimé / [éd.] Université nationale du Rwanda / Ruhengeri Éd. universitaires du Rwanda 1991   ",
					ID:       "35477843",
					Source:   "bnf",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "340",
					Marc21Code:  "edt",
					RoleName:    "Editeur scientifique"},
					Citation: "Contribution à la bibliographie nationale du Rwanda Texte imprimé ; publ. sous les auspices de l'Université nationale du Rwanda.. / par Albert Levesque / Moncton, [Nouveau Brunswick, Canada] Imprimerie acadienne 1974   ",
					ID:       "35268651",
					Source:   "bnf",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "990",
					Marc21Code:  "Fonction non précisée",
					RoleName:    "Sujet"},
					Citation: "Textes légaux et réglementaires de l'Université nationale du Rwanda de 1963 à 1985  / Université nationale du Rwanda / Butare : Secrétariat général de l'Université , [1986]",
					ID:       "020539835",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "990",
					Marc21Code:  "Fonction non précisée",
					RoleName:    "Sujet"},
					Citation: "Une  nouvelle page de la nouvelle université rwandaise  : de Georges-Henri Lévesque à Mike O'Neil  / Léonard Nduwayo / Paris : les Impliqués éditeur , DL 2014, cop. 2014",
					ID:       "183483723",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "990",
					Marc21Code:  "Fonction non précisée",
					RoleName:    "Sujet"},
					Citation: "L'Université nationale du Rwanda  [Texte imprimé]  : cinquantenaire  : de l'Institut Saint Jean à NUR  / Léonard Nduwayo  ; préface du professeur Venant Ntabomvura,...  ; postface du Dr Jean-Damascène Ntawukuliryayo,... / Lille : Éd. Sources du Nil , DL 2013, cop. 2013",
					ID:       "169937283",
					Source:   "sudoc",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "990",
					Marc21Code:  "Fonction non précisée",
					RoleName:    "Sujet"},
					Citation: "Une nouvelle page de la nouvelle université rwandaise Texte imprimé / Léonard Nduwayo / Paris les Impliqués éditeur DL 2014 14-Condé-sur-Noireau Impr. Corlet numérique ",
					ID:       "44243510",
					Source:   "bnf",
					URI:      "",
					URL:      ""},
				{AuthorityRole: AuthorityRole{
					UnimarcCode: "990",
					Marc21Code:  "Fonction non précisée",
					RoleName:    "Sujet"},
					Citation: "L'Université nationale du Rwanda Texte imprimé ; préface du professeur Venant Ntabomvura,... postface du Dr Jean-Damascène Ntawukuliryayo,... / Léonard Nduwayo / Lille Éd. Sources du Nil DL 2013 impr. en Lettonie  ",
					ID:       "43602723",
					Source:   "bnf",
					URI:      "",
					URL:      ""},
			},
			Valid: true,
		},
		{
			Description: "Docs for single invalid PPN",
			Input:       "02797524",
			Expected:    nil,
			Valid:       false,
		},
	}
	for _, test := range docsGetTestCases {
		actual, err := DocsGet(test.Input)
		if err != nil && !test.Valid {
			t.Logf("PASS %s: got %v", test.Description, err)
		}
		if reflect.DeepEqual(test.Expected, actual) {
			t.Logf("PASS %s", test.Description)
		} else {
			t.Fatalf("FAIL for %s (%s): expected %v, actual result was %v", test.Input, test.Description, test.Expected, actual)
		}
	}

}
